### ISSUE TITLE
Problem with CQRS_ID

### ISSUE THREAD

**Issue by CamiloAguilarL** [cloudblue/django-cqrs#69]
I've been working with Django CQRS lately and today I had a problem with it. Following the Getting started section from the docs all was working nice but when I tried to add an entity either from the django admin or with the sync command, it throws this error for each entity:

('CQRS is failed: pk = 7 (student), correlation_id = None, retries = 0.',)
No model with such CQRS_ID: student.
Model for cqrs_id student is not found.

Reading the example and the docs didn't help me. Thanks in advance

**Comment by maxipavlovic** [comment]
Hi, @CamiloAguilarL. Let's see.

You are getting this error on Replica side after configuring everything from this section https://django-cqrs.readthedocs.io/en/latest/getting_started.html#replica-service ?

**Comment by maxipavlovic** [comment]
@CamiloAguilarL I've checked your CQRS project and made a fork to try myself if something goes wrong.

Seems everything is alright for me in this branch without any code changes (only configuration ones):
https://github.com/maxipavlovic/proyectoCQRS/tree/check-cqrs-problem

I've added `docker-compose` to run the environment all together and then created a Student object in master container and verified that this Student was CQRSed to replica service correctly.

**Comment by maxipavlovic** [comment]
Closing as couldn't reproduce and there was no response for a while.
